#######################################################
#              MeltItems v1.5 config.yml              #
#######################################################
# MeltItems v1.5 by Arionas_MC
# Check out my other plugins here: https://www.spigotmc.org/resources/authors/arionas_mc.202993/
# MeltItems' source code:

recipes:
  - 'DIAMOND_SWORD,DIAMOND,2'
  - 'DIAMOND_AXE,DIAMOND,3'
  - 'DIAMOND_SHOVEL,DIAMOND,1'
  - 'DIAMOND_HOE,DIAMOND,2'
  - 'DIAMOND_PICKAXE,DIAMOND,3'
  - 'IRON_SWORD,IRON_INGOT,2'
  - 'IRON_AXE,IRON_INGOT,3'
  - 'IRON_SHOVEL,IRON_INGOT,1'
  - 'IRON_HOE,IRON_INGOT,2'
  - 'IRON_PICKAXE,IRON_INGOT,3'
  - 'GOLDEN_SWORD,GOLD_INGOT,2'
  - 'GOLDEN_AXE,GOLD_INGOT,3'
  - 'GOLDEN_SHOVEL,GOLD_INGOT,1'
  - 'GOLDEN_HOE,GOLD_INGOT,2'
  - 'GOLDEN_PICKAXE,GOLD_INGOT,3'
  - 'STONE_SWORD,STONE,2'
  - 'STONE_AXE,STONE,3'
  - 'STONE_SHOVEL,STONE,1'
  - 'STONE_HOE,STONE,2'
  - 'STONE_PICKAXE,STONE,3'
  - 'WOODEN_SWORD,COAL,2'
  - 'WOODEN_AXE,COAL,3'
  - 'WOODEN_SHOVEL,COAL,1'
  - 'WOODEN_HOE,COAL,2'
  - 'WOODEN_PICKAXE,COAL,3'
