#######################################################
#              MeltItems v1.5 config.yml              #
#######################################################
# MeltItems v1.5 by Arionas_MC
# Check out my other plugins here: https://www.spigotmc.org/resources/authors/arionas_mc.202993/
# MeltItems' source code:

recipes:
  - 'DIAMOND_SWORD,DIAMOND,2'
  - 'DIAMOND_AXE,DIAMOND,3'
  - 'DIAMOND_SPADE,DIAMOND,1'
  - 'DIAMOND_HOE,DIAMOND,2'
  - 'DIAMOND_PICKAXE,DIAMOND,3'
  - 'IRON_SWORD,IRON_INGOT,2'
  - 'IRON_AXE,IRON_INGOT,3'
  - 'IRON_SPADE,IRON_INGOT,1'
  - 'IRON_HOE,IRON_INGOT,2'
  - 'IRON_PICKAXE,IRON_INGOT,3'
  - 'GOLD_SWORD,GOLD_INGOT,2'
  - 'GOLD_AXE,GOLD_INGOT,3'
  - 'GOLD_SPADE,GOLD_INGOT,1'
  - 'GOLD_HOE,GOLD_INGOT,2'
  - 'GOLD_PICKAXE,GOLD_INGOT,3'
  - 'STONE_SWORD,STONE,2'
  - 'STONE_AXE,STONE,3'
  - 'STONE_SPADE,STONE,1'
  - 'STONE_HOE,STONE,2'
  - 'STONE_PICKAXE,STONE,3'
  - 'WOOD_SWORD,COAL,2'
  - 'WOOD_AXE,COAL,3'
  - 'WOOD_SPADE,COAL,1'
  - 'WOOD_HOE,COAL,2'
  - 'WOOD_PICKAXE,COAL,3'
