#######################################################
#              MeltItems v1.5 config.yml              #
#######################################################
# MeltItems v1.5 by Arionas_MC
# Check out my other plugins here: https://www.spigotmc.org/resources/authors/arionas_mc.202993/
# MeltItems' source code: https://github.com/ArionasMC/MeltItems

# This is the recipes list. Here you can add your own Furnace Recipes!
# Syntax: '<source>,<result>,<model>/<quantity>,<experience>,<time>'
# - <source> = The item you want to melt
# - <result> = The result item (this item replaces the %material% placeholder below in models list)
# - <model> = The recipe's model (IT IS REQUIRED THAT THE ITEMS HAS DURABILITY)
# - <quantity> = The quantity of the result (ONLY USED WHEN THE ITEM HAS NO DURABILITY e.g a bucket)
# - <experience> = Exp gained
# - <time> = The time required for the recipe to be completed
# NOTE: You can find all appropriate item names here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
recipes:
  - 'DIAMOND_SWORD,DIAMOND,sword_standard,0,5'
  - 'DIAMOND_AXE,DIAMOND,axe_standard,0,5'
  - 'DIAMOND_SHOVEL,DIAMOND,shovel_standard,0,5'
  - 'DIAMOND_HOE,DIAMOND,sword_standard,0,5'
  - 'DIAMOND_PICKAXE,DIAMOND,axe_standard,0,5'
  - 'IRON_SWORD,IRON_INGOT,sword_standard,0,5'
  - 'IRON_AXE,IRON_INGOT,axe_standard,0,5'
  - 'IRON_SHOVEL,IRON_INGOT,shovel_standard,0,5'
  - 'IRON_HOE,IRON_INGOT,sword_standard,0,5'
  - 'IRON_PICKAXE,IRON_INGOT,axe_standard,0,5'
  - 'GOLDEN_SWORD,GOLD_INGOT,sword_standard,0,5'
  - 'GOLDEN_AXE,GOLD_INGOT,axe_standard,0,5'
  - 'GOLDEN_SHOVEL,GOLD_INGOT,shovel_standard,0,5'
  - 'GOLDEN_HOE,GOLD_INGOT,sword_standard,0,5'
  - 'GOLDEN_PICKAXE,GOLD_INGOT,axe_standard,0,5'
  - 'STONE_SWORD,STONE,sword_standard,0,5'
  - 'STONE_AXE,STONE,axe_standard,0,5'
  - 'STONE_SHOVEL,STONE,shovel_standard,0,5'
  - 'STONE_HOE,STONE,sword_standard,0,5'
  - 'STONE_PICKAXE,STONE,axe_standard,0,5'
  - 'WOODEN_SWORD,COAL,sword_standard,0,5'
  - 'WOODEN_AXE,COAL,axe_standard,0,5'
  - 'WOODEN_SHOVEL,COAL,shovel_standard,0,5'
  - 'WOODEN_HOE,COAL,sword_standard,0,5'
  - 'WOODEN_PICKAXE,COAL,axe_standard,0,5'
  - 'DIAMOND_HELMET,DIAMOND,helmet_standard,0,10'
  - 'DIAMOND_CHESTPLATE,DIAMOND,chest_standard,0,10'
  - 'DIAMOND_LEGGINGS,DIAMOND,legs_standard,0,10'
  - 'DIAMOND_BOOTS,DIAMOND,boots_standard,0,10'
  - 'IRON_HELMET,IRON_INGOT,helmet_standard,0,10'
  - 'IRON_CHESTPLATE,IRON_INGOT,chest_standard,0,10'
  - 'IRON_LEGGINGS,IRON_INGOT,legs_standard,0,10'
  - 'IRON_BOOTS,IRON_INGOT,boots_standard,0,10'
  - 'GOLDEN_HELMET,GOLD_INGOT,helmet_standard,0,10'
  - 'GOLDEN_CHESTPLATE,GOLD_INGOT,chest_standard,0,10'
  - 'GOLDEN_LEGGINGS,GOLD_INGOT,legs_standard,0,10'
  - 'GOLDEN_BOOTS,GOLD_INGOT,boots_standard,0,10'
  - 'BUCKET,IRON_INGOT,3,0,1'
  - 'LAVA_BUCKET,POPPY,3,10,1'

# This is the models list. A model affects the results of the recipes
# In each model you can add a line with the following syntax: '<durability>,<material>,<quantity>'
# - <durability> represents the durability percentage at which and below the following line has an effect
# - <material> can be either a material or the %material% placeholder which will be replaced as mentioned above
# - <quantity> is the quantity of <material> as the recipe's result
models:
  sword_standard:
    - '100:%material%,2'
    - '50:%material%,1'
    - '25:COAL,1'
  axe_standard:
    - '100:%material%,3'
    - '75:%material%,2'
    - '40:%material%,1'
    - '20:COAL,1'
  shovel_standard:
    - '100:%material%,1'
    - '50:COAL,1'
  helmet_standard:
    - '100:%material%,5'
    - '50:%material%,3'
    - '30:%material%,1'
    - '15:COAL,1'
  chest_standard:
    - '100:%material%,8'
    - '70:%material%,6'
    - '50:%material%,4'
    - '30:%material%,2'
    - '15:COAL,1'
  legs_standard:
    - '100:%material%,7'
    - '60:%material%,4'
    - '30:%material%,2'
    - '15:COAL,1'
  boots_standard:
    - '100:%material%,4'
    - '50:%material%,2'
    - '15:COAL,1'
